// Product CRUD
export const PRODUCT_LIST_REQUEST = "PRODUCT_LIST_REQUEST";
export const PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS";
export const PRODUCT_LIST_FAIL = "PRODUCT_LIST_FAIL";

export const FETCH_PRODUCT_REQUEST = "FETCH_PRODUCT_REQUEST";
export const FETCH_PRODUCT_SUCCESS = "FETCH_PRODUCT_SUCCESS";
export const FETCH_PRODUCT_FAIL = "FETCH_PRODUCT_FAIL";

export const FETCH_LATEST_PRODUCT_REQUEST = "FETCH_LATEST_PRODUCT_REQUEST";
export const FETCH_LATEST_PRODUCT_SUCCESS = "FETCH_LATEST_PRODUCT_SUCCESS";
export const FETCH_LATEST_PRODUCT_FAIL = "FETCH_LATEST_PRODUCT_FAIL";

// Products you may like
export const PRODUCTS_YOU_MAY_LIKE_REQUEST = "PRODUCTS_YOU_MAY_LIKE_REQUEST";
export const PRODUCTS_YOU_MAY_LIKE_SUCCESS = "PRODUCTS_YOU_MAY_LIKE_SUCCESS";
export const PRODUCTS_YOU_MAY_LIKE_FAIL = "PRODUCTS_YOU_MAY_LIKE_FAIL";


// Settings
export const CHANGE_LANGUAGE = "CHANGE_LANGUAGE";
export const CHANGE_CURRENCY = "CHANGE_CURRENCY";
export const CHANGE_COUNTRY = "CHANGE_COUNTRY";


// Update Language Settings (to DB)
export const USER_UPDATE_LANGUAGE_REQUEST = "USER_UPDATE_LANGUAGE_REQUEST";
export const USER_UPDATE_LANGUAGE_SUCCESS = "USER_UPDATE_LANGUAGE_SUCCESS";
export const USER_UPDATE_LANGUAGE_FAIL = "USER_UPDATE_LANGUAGE_FAIL";

// Change Settings (not login)
export const UPDATE_SETTINGS = "UPDATE_SETTINGS";
export const UPDATE_SETTINGS_RESET = "UPDATE_SETTINGS_RESET";
